### ISSUE TITLE
FEATURE: add cropping functionality to PiP window

### ISSUE THREAD

**Issue by jochmann** [pxi-gmbh/pipfy#2]
in order to arrange the video-window with other app windows on screen it would be nice to have three aspect ratios as options:

- 4:3 (landscape orientation. should be default)
- 3:4 (portrait orientation)
- 1:1 (square image)

simply editing the height and width of the canvas-element crops the PiP-window. However, the crop affects the image from bottom & right. If the image could be centered so that the camera can stay centered on the person in front of it, that would make handling the app much easier.

**Comment by jochmann** [comment]
as an advanced feature addendum: 

- is masking possible (to have the PiP window appear as a circle, for example) on the canvas element?
- is it possible to create a green screen effect (chroma-key by applying a CSS-filter to turn "green" into a fully transparent alpha channel)?

**Comment by gaenseklein** [comment]
cropping: possible
masking: possible
green-screen-effect: should be possible

as we are working with canvas frame-by-frame all of this *should* be possible. Remember, we have a full arsenal of options how to draw each image and can alter it the way we want directly, not only by css. But I would not recommend to do heavy stuff, as this is all happening in javascript in a browser in an enviroment not really fit to do such calculations *fast*. Remember: if you want to have a framerate of 25fps every frame has only 40ms to be rendered fully. i see a drop in framerate which is not only because we are maxing framerate to 25fps (which human eye should not see any difference) so i think by flipping often we dont really get 25fps. Now imaging what happens with more complex stuff.  
cropping: no problem. masking: should be possible. green-screen-effect: I dont think most machines could handle this fast enough. 
But we can give it a try...

**Comment by jochmann** [comment]
I confused the properties of "hue-rotate" css-filter. I thought there was a possibility of switching one hue for a specific color (with full transparency) but that's not the way the filter works, obviously.

So: no to js-filter for green screen-effects.

cropping + masking the image to a circle would be nice and useful additions. We can add special frames and embellishments over time, if there is demand for it.

I have noticed that we may need to "normalize" the camera input to a lower resolution for the canvas render. If the original camera image is HD and 1080px wide, the canvas will currently only display a cropped out top-left corner.

**Comment by gaenseklein** [comment]
on second thought i am not shure if cropping and masking would result in the desired effect as we are not rendering the canvas directly but through a video-stream and i dont think this video would have an alpha-channel. as the pip does not have any css-styling possible i think it will always be somewhat of a square and the "not-filled" part (from the alpha-channel) would be simply black.

**Comment by jochmann** [comment]
yes, I would expect the OS to determine the background of the PiP window - and at least on Mac there is the regular background (probably white) and drop shadow. if it's an easy test, perhaps we're lucky with the background on some OS? either way it's a very minor cosmetic enhancement we can live without.

for the rectangular crop I think we just need to center the video relative to the canvas and set height/width on the canvas element accordingly.

**Comment by jochmann** [comment]
We'll take the current cropping functionality as a baseline and only add UI improvements. Done.
